#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
EXP="$DIR/expandCSVjsPsych"

# Clean previous runs
rm -f -- ./*_clean.csv all.csv

# Apply the python script to each file
for file in *.csv; do
    $EXP "$file" "${file%.csv}_clean.csv"
done

pattern="*_clean.csv"
files=($pattern)

# Get the header from one file
head -n 1 "${files[0]}" >> "all.csv"

# Append all the others
for file in $pattern; do
    tail -n +2 "$file" >> "all.csv"
done

# Cleanup tmp files
rm ./*_clean.csv
