var material = [

  { audio: "audio/item_1_1.mp3",
    sentence: "Kwesi knows whoSG came to visit you yesterday, namely Esi.",
    id: "item.1",
    type: "critical",
    condition: "SG-match",
  },

  { audio: "audio/item_1_5.mp3",
    sentence: "Yaw knows whoSG arrived last night, namely Kwame.",
    id: "item.2",
    type: "critical",
    condition: "SG-match",
  },

  { audio: "audio/item_1_9.mp3",
    sentence: "Kwaku knows whoSG missed the lecture, namely Kofi.",
    id: "item.3",
    type: "critical",
    condition: "SG-match",
  },

  { audio: "audio/item_2_4.mp3",
    sentence: "Akwasi knows whoSG passed the exam, namely Awo, Akosua and Manu.",
    id: "item.4",
    type: "critical",
    condition: "SG-mismatch",
  },

  { audio: "audio/item_2_8.mp3",
    sentence: "Mensah knows whoSG missed the train, namely Baaba, Esi and Ekuwa.",
    id: "item.5",
    type: "critical",
    condition: "SG-mismatch",
  },

  { audio: "audio/item_2_12.mp3",
    sentence: "Aba knows whoSG plays in a band, namely Badu, Kojo and Kwame.",
    id: "item.6",
    type: "critical",
    condition: "SG-mismatch",
  },

  { audio: "audio/item_3_3.mp3",
    sentence: "Ekow knows whoPL handed in the final assignment, namely Ebo.",
    id: "item.7",
    type: "critical",
    condition: "PL-mismatch",
  },

  { audio: "audio/item_3_7.mp3",
    sentence: "Kwaku knows whoPL came late to the party, namely Kofi.",
    id: "item.8",
    type: "critical",
    condition: "PL-mismatch",
  },

  { audio: "audio/item_3_11.mp3",
    sentence: "Afiba knows whoPL cheated on the exam, namely Yaw.",
    id: "item.9",
    type: "critical",
    condition: "PL-mismatch",
  },

  { audio: "audio/item_4_2.mp3",
    sentence: "Kofi knows whoPL cleaned the kitchen last week, namely Afiba, Kojo and Adu.",
    id: "item.10",
    type: "critical",
    condition: "PL-match",
  },

  { audio: "audio/item_4_6.mp3",
    sentence: "Ebo knows whoPL called yesterday, namely Ekuwa, Yaw and Kofi.",
    id: "item.11",
    type: "critical",
    condition: "PL-match",
  },

  { audio: "audio/item_4_10.mp3",
    sentence: "Kojo knows whoPL went on holiday, namely Akua, Akosua and Abena.",
    id: "item.12",
    type: "critical",
    condition: "PL-match",
  },

  { audio: "audio/filler_1_1.mp3",
    sentence: "Kweku knows whoSG cleaned up.",
    id: "item.13",
    type: "filler",
    condition: "no-follow-up",
  },

  { audio: "audio/filler_1_2.mp3",
    sentence: "Kwabena knows whoSG forgot his birthday.",
    id: "item.14",
    type: "filler",
    condition: "no-follow-up",
  },

  { audio: "audio/filler_1_3.mp3",
    sentence: "Peter knows whoSG went to the concert.",
    id: "item.15",
    type: "filler",
    condition: "no-follow-up",
  },

  { audio: "audio/filler_1_4.mp3",
    sentence: "Adwoa knows whoSG spoke at the conference.",
    id: "item.16",
    type: "filler",
    condition: "no-follow-up",
  },

  { audio: "audio/filler_1_5.mp3",
    sentence: "Akua knows whoSG came to the wedding.",
    id: "item.17",
    type: "filler",
    condition: "no-follow-up",
  },

  { audio: "audio/filler_2_1.mp3",
    sentence: "Kofi discovered whoSG cleaned the kitchen last week, namely Afiba, Ama and Kofi.",
    id: "item.18",
    type: "filler",
    condition: "other-predicate",
  },

  { audio: "audio/filler_2_2.mp3",
    sentence: "Yaw heard whoSG arrived last night, namely Kwame, Ebo and Adu.",
    id: "item.19",
    type: "filler",
    condition: "other-predicate",
  },

  { audio: "audio/filler_2_3.mp3",
    sentence: "Abena remembers whoSG laughed at her, namely Awo, Afiba and Ekuwa.",
    id: "item.20",
    type: "filler",
    condition: "other-predicate",
  },

  { audio: "audio/filler_3_1.mp3",
    sentence: "whoSG cleaned up knows Kweku (the one who cleaned up knows Kweku).",
    id: "item.21",
    type: "filler",
    condition: "ungrammatical",
  },

  { audio: "audio/filler_3_2.mp3",
    sentence: "whoSG forgot his birthday knows Kwabena (the one who forgot his birthday knows Kwabena).",
    id: "item.22",
    type: "filler",
    condition: "ungrammatical",
  },

  { audio: "audio/filler_3_3.mp3",
    sentence: "whoSG went to the concert Peter knows.",
    id: "item.23",
    type: "filler",
    condition: "ungrammatical",
  },

  { audio: "audio/filler_3_4.mp3",
    sentence: "whoSG spoke at the conference Adwoa knows.",
    id: "item.24",
    type: "filler",
    condition: "ungrammatical",
  },

  { audio: "audio/filler_3_5.mp3",
    sentence: "knows Akua whoSG came to the wedding (Akua knows whoSG came to the wedding).",
    id: "item.25",
    type: "filler",
    condition: "ungrammatical",
  },

  { audio: "audio/filler_3_6.mp3",
    sentence: "knows Afiba whoSG cheated on the exam (Afiba knows whoSG cheated on the exam).",
    id: "item.26",
    type: "filler",
    condition: "ungrammatical",
  },

];